// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmuRAjCS38xqDorHGvStD46MYas5_2zo',
    appId: '1:82951590787:web:e9ffedeb4af64e43cc1cb6',
    messagingSenderId: '82951590787',
    projectId: 'springwel-92cdc',
    authDomain: 'springwel-92cdc.firebaseapp.com',
    storageBucket: 'springwel-92cdc.appspot.com',
    measurementId: 'G-0E0X9F8RQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKIS5Xo5APALS1zBS5kMW7z38siDQDHk',
    appId: '1:82951590787:android:d4938dcf7293b72ecc1cb6',
    messagingSenderId: '82951590787',
    projectId: 'springwel-92cdc',
    storageBucket: 'springwel-92cdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIyNJP0i3Rj4yKyyBfj7VrmVhIKP051Ks',
    appId: '1:82951590787:ios:1d6c2875e418693bcc1cb6',
    messagingSenderId: '82951590787',
    projectId: 'springwel-92cdc',
    storageBucket: 'springwel-92cdc.appspot.com',
    iosClientId: '82951590787-irlo65m6hc5roodq8n8c609utiack075.apps.googleusercontent.com',
    iosBundleId: 'com.example.springwel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIyNJP0i3Rj4yKyyBfj7VrmVhIKP051Ks',
    appId: '1:82951590787:ios:1d6c2875e418693bcc1cb6',
    messagingSenderId: '82951590787',
    projectId: 'springwel-92cdc',
    storageBucket: 'springwel-92cdc.appspot.com',
    iosClientId: '82951590787-irlo65m6hc5roodq8n8c609utiack075.apps.googleusercontent.com',
    iosBundleId: 'com.example.springwel',
  );
}
